name: generate plantuml
on: push
jobs:
  render_plantuml:
    runs-on: ubuntu-latest
    name: Render PlantUML files
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Render PlantUML files
      uses: ghcr.io/racklet/render-plantuml-action@v1
      id: render
      with:
        formats: 'svg'
        sub-dirs: './uml'
        skip-dirs: '.git'
        log-level: 'info'
    - name: Print the rendered files
      run: |
        echo "The following files were generated: ${{ steps.render.outputs.rendered-files }}"
    - uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'Automatically render PlantUML files'
        add: "${{ steps.render.outputs.rendered-files }}"
